version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GitRuntimeAssetsAZURESPROProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser
  gitUsername: siqagituser
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  version: "1.0"
  gitServerName: siqagituser
  gitUrl: https://github.com/vijetadixit
  gitUsername: siqagituser
  gitBranch: Test
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: softwareag
services:
- serviceName: project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_11Nov
  packages:
  - name: SIQA_GitRuntimeAssetsAZURESPROProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBTest
  packages:
  - name: SIQA_GitRuntimeAssetsAZURESPROProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: project.siqa_gitruntimeassetsazurespro.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GitRuntimeAssetsAZURESPROProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: project.siqa_gitruntimeassetsazurespro.integrations:SIQA_E2E_Mon_Test
  packages:
  - name: SIQA_GitRuntimeAssetsAZURESPROProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2017
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2017
- serviceName: project.siqa_gitruntimeassetsazurespro.integrations:SIQA_ThirdPPEdgeFS
  packages:
  - name: SIQA_GitRuntimeAssetsAZURESPROProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:ComplexFS
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:Basic_Flow
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.math:divideInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2017
- serviceName: pub.math:subtractInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2017
- serviceName: pub.math:multiplyIntList
  packages:
  - name: WmPublic
    version: 11.1.0.0.2017
- serviceName: Basics_1:mapservice
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:TryCatch
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Map_1:TestFlow
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: REST_1_1.CurrentDateAndTime:_get
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2017
- serviceName: pub.string:objectToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2017
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2017
- serviceName: SOAP_1_1:showDateAndTime
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
configurationVariables:
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionManagerSettings.startupBackoffSecs
  : "10"
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.keyStore
  : ""
  jdbc.jdbcTestPool.spyenabled: "false"
  jdbc.jdbcTestPool.snoopenabled: "false"
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionManagerSettings.maximumPoolSize
  : "10"
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.user
  : sa
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionManagerSettings.startupRetryCount
  : "0"
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  jdbc.jdbcTestPool.expireTime: "60000"
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionEnabled
  : "false"
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.databaseName
  : SIQACloud
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.serverName
  : vmiboint01
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.portNumber
  : "1433"
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.dbType
  : MSSQL
  ? artConnection.SIQA_GitRuntimeAssetsAZURESPROProject.project.siqa_gitruntimeassetsazurespro.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_11Nov.connectionSettings.trustStore
  : ""
  jdbc.jdbcTestPool.useSSL: "false"
